name: "publish"

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

concurrency:
  group: publish-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  prepare:
    uses: ./.github/workflows/_prepare-release.yml
    permissions:
      contents: write

  macos:
    needs: prepare
    uses: ./.github/workflows/release-macos.yml
    with:
      release_tag: ${{ needs.prepare.outputs.tag }}
      version: ${{ needs.prepare.outputs.version }}
    secrets: inherit

  linux:
    needs: prepare
    uses: ./.github/workflows/release-linux.yml
    with:
      release_tag: ${{ needs.prepare.outputs.tag }}
      version: ${{ needs.prepare.outputs.version }}
    secrets: inherit

  windows:
    needs: prepare
    uses: ./.github/workflows/release-windows.yml
    with:
      release_tag: ${{ needs.prepare.outputs.tag }}
      version: ${{ needs.prepare.outputs.version }}
    secrets: inherit
